#!/bin/bash

. ~/.config/hyprland-de/globalConfigs.sh

if [ -z "$1" ]; then
    echo "No path supplied"
    exit 1
fi

RAW_PATH="$1"
RESOLVED_PATH="$(python3 - "$RAW_PATH" <<'PY'
import os
import sys

candidate = os.path.expandvars(os.path.expanduser(sys.argv[1]))
print(os.path.abspath(candidate))
PY
)"

if [ ! -f "$RESOLVED_PATH" ]; then
    echo "File doesn't exist"
    exit 1
fi

echo "$RESOLVED_PATH" > ~/.config/hyprland-de/wallpaper.conf

cat <<EOF > ~/.config/hypr/hyprpaper.conf
# Do not edit this file, your changes will be overwritten
preload=$RESOLVED_PATH
wallpaper=,$RESOLVED_PATH
EOF

nohup wallust run "$RESOLVED_PATH" > /dev/null >&/dev/null &
nohup matugen --contrast "$HLDE_MATUGEN_CONTRAST" image "$RESOLVED_PATH" > /dev/null >&/dev/null &

if [ "$HYPRLAND_INSTANCE_SIGNATURE" = "" ]; then
    echo "Done!"
    exit 0
fi

if [ -z "$HLDE_NO_HYPRPAPER" ]; then
    killall hyprpaper > /dev/null || echo ""
    hyprctl dispatch exec hyprpaper || echo ""
fi
killall walker > /dev/null || echo ""
GSK_RENDERER=cairo nohup walker --gapplication-service >&/dev/null &

echo "Done!"
