-- Scythe's Hyprland config. See wiki for full options:
-- https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

-- DMS_STARTUP_BEGIN
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
end)
-- DMS_STARTUP_END

require("config.look")
require("config.input")
require("config.displays")
require("config.apps")
require("config.windows")
require("config.workspaces")
require("config.media")
require("config.session")
require("config.dock")

-- DMS integration, loaded last so it wins any override.
-- dms.colors, dms.layout and dms.binds stay unloaded.
require("dms.cursor")
require("dms.windowrules")
require("dms.binds-user")
require("dms.outputs")
