theme = "kanagawa"

[editor]
end-of-line-diagnostics = "hint"
auto-pairs = false

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
A-w = ":toggle-option soft-wrap.enable"
A-h = ":toggle-option lsp.display-inlay-hints"
A-d = ":toggle inline-diagnostics.cursor-line warning disable"

# Disable diagnostics while in insert. Pt1
i = [":set end-of-line-diagnostics disable", "insert_mode"]
I = [":set end-of-line-diagnostics disable", "insert_at_line_start"]
a = [":set end-of-line-diagnostics disable", "append_mode"]
A = [":set end-of-line-diagnostics disable", "insert_at_line_end"]
o = [":set end-of-line-diagnostics disable", "open_below"]
O = [":set end-of-line-diagnostics disable", "open_above"]

[keys.insert]

# Disable diagnostics while in insert. Pt2
"esc"   = [":set end-of-line-diagnostics hint", "normal_mode"]
